version: '3'

services:
  database:
    container_name: database
    image: 'mysql:8.0'
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3307:3306'
  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '12345:6379'
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker-config/Dockerfile
    ports:
      - '14000:80'
    depends_on:
      - database
      - redis
    volumes:
      - .:/var/www/html

volumes:
  database_data:
